Repository muesli/beehive, pull requests merged in 2020-10, with the labels that each got.

#334 Support parse_mode for telegram
  bees/telegrambee/telegrambee.go
  bees/telegrambee/telegrambeefactory.go
Labels: enhancement, hive

#340 Improve filters interface
  filters/filters.go
  filters/template/templatefilter.go
Labels: improvement

#342 Fix conversion warning in tests introduced by Go 1.15
  bees/notificationbee/notificationbee_unix.go
Labels: bug

#346 Attempt to fix Facebook auth scopes (#264)
  bees/facebookbee/facebookbee.go
  bees/facebookbee/facebookbeefactory.go
Labels: bug, hive

#348 Remove user stream and events from TwitterBee
  bees/twitterbee/twitterbee.go
  bees/twitterbee/twitterbeefactory.go
Labels: bug, hive
